name: Build emscripten project and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v12
        
      - name: Build the web app
        working-directory: ${{github.workspace}}
        run: ./build.sh
        
      - name: Clean CMake cache
        working-directory: ${{github.workspace}}/build
        run: rm -rf CMakeFiles *.cmake
        
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/build
        
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
